=== Tony7466/datacrow/modules/datacrow-resources/modules/data/editiontype.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xsd:element name="data-crow-objects">
    <xsd:complexType>
        <xsd:sequence>
            <xsd:element name="edition-type-items" type ="edition-type-items-type"/>
        </xsd:sequence>
    </xsd:complexType>
</xsd:element>

    <xsd:complexType name="edition-type-items-type" >
        <xsd:sequence>
            <xsd:element type="edition-type-type" name="edition-type" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="edition-type-type" >
        <xsd:sequence>
            <xsd:element name="datacrow-module-index" type="xsd:integer" nillable="true" minOccurs="0" />
            <xsd:element name="picture-01" type="xsd:string" nillable="true" minOccurs="0"/>
            <xsd:element name="picture-02" type="xsd:string" nillable="true" minOccurs="0"/>
            <xsd:element name="picture-03" type="xsd:string" nillable="true" minOccurs="0"/>
            <xsd:element name="picture-04" type="xsd:string" nillable="true" minOccurs="0"/>
            <xsd:element name="picture-05" type="xsd:string" nillable="true" minOccurs="0"/>
            <xsd:element name="picture-06" type="xsd:string" nillable="true" minOccurs="0"/>
            <xsd:element name="picture-07" type="xsd:string" nillable="true" minOccurs="0"/>
            <xsd:element name="picture-08" type="xsd:string" nillable="true" minOccurs="0"/>
            <xsd:element name="picture-09" type="xsd:string" nillable="true" minOccurs="0"/>
            <xsd:element name="picture-10" type="xsd:string" nillable="true" minOccurs="0"/>
            <xsd:element name="name" type="xsd:string" nillable="true" minOccurs="0"/>
            <xsd:element name="alternative-names" type="xsd:string" nillable="true" minOccurs="0"/>
            <xsd:element name="modified" type="xsd:date" nillable="true" minOccurs="0"/>
            <xsd:element name="created" type="xsd:date" nillable="true" minOccurs="0"/>
            <xsd:element name="icon" type="xsd:string" nillable="true" minOccurs="0"/>
            <xsd:element name="item" type="xsd:string" nillable="true" minOccurs="0"/>
            <xsd:element name="label" type="xsd:string" nillable="true" minOccurs="0"/>
            <xsd:element name="id" type="xsd:string" nillable="true" minOccurs="0"/>
        </xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== Tony7466/datacrow/Modules/datacrow-resources/modules/data/editiontype.xml
<?xml version="1.0" encoding="UTF-8" ?>
<data-crow-objects xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="editiontype.xsd">
    <editiontype-items>
            <editiontype>
                <picture-01></picture-01>
                <picture-02></picture-02>
                <picture-03></picture-03>
                <picture-04></picture-04>
                <picture-05></picture-05>
                <picture-06></picture-06>
                <picture-07></picture-07>
                <picture-08></picture-08>
                <picture-09></picture-09>
                <picture-10></picture-10>
                <name>First Edition</name>
                <modified>2024-10-01</modified>
                <created>2024-10-01</created>
                <label>First Edition</label>
                <id>101744746097306</id>
            </editiontype>
        </editiontype-items>
</data-crow-objects>

=== Tony7466/datacrow/modules/datacrow-resources/modules/data/editiontype.xml
<?xml version="1.0" encoding="UTF-8" ?>
<data-crow-objects xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="editiontype.xsd">
    <edition-type-items>
            <edition-type>
                <datacrow-module-index>1300000</datacrow-module-index>
                <picture-01></picture-01>
                <picture-02></picture-02>
                <picture-03></picture-03>
                <picture-04></picture-04>
                <picture-05></picture-05>
                <picture-06></picture-06>
                <picture-07></picture-07>
                <picture-08></picture-08>
                <picture-09></picture-09>
                <picture-10></picture-10>
                <name>First Edition</name>
                <modified>2025-04-17</modified>
                <created>2025-04-17</created>
                <label>First Edition</label>
                <id>101744746097306</id>
            </edition-type>
        </edition-type-items>
</data-crow-objects>
