=== Tony7466/datacrow/modules/datacrow-resources/modules/data/movie_genre.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xsd:element name="data-crow-objects">
    <xsd:complexType>
        <xsd:sequence>
            <xsd:element name="genre-items" type ="genre-items-type"/>
        </xsd:sequence>
    </xsd:complexType>
</xsd:element>

    <xsd:complexType name="genre-items-type" >
        <xsd:sequence>
            <xsd:element type="genre-type" name="genre" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="genre-type" >
        <xsd:sequence>
            <xsd:element name="datacrow-module-index" type="xsd:integer" nillable="true" minOccurs="0" />
            <xsd:element name="picture-01" type="xsd:string" nillable="true" minOccurs="0"/>
            <xsd:element name="picture-02" type="xsd:string" nillable="true" minOccurs="0"/>
            <xsd:element name="picture-03" type="xsd:string" nillable="true" minOccurs="0"/>
            <xsd:element name="picture-04" type="xsd:string" nillable="true" minOccurs="0"/>
            <xsd:element name="picture-05" type="xsd:string" nillable="true" minOccurs="0"/>
            <xsd:element name="picture-06" type="xsd:string" nillable="true" minOccurs="0"/>
            <xsd:element name="picture-07" type="xsd:string" nillable="true" minOccurs="0"/>
            <xsd:element name="picture-08" type="xsd:string" nillable="true" minOccurs="0"/>
            <xsd:element name="picture-09" type="xsd:string" nillable="true" minOccurs="0"/>
            <xsd:element name="picture-10" type="xsd:string" nillable="true" minOccurs="0"/>
            <xsd:element name="name" type="xsd:string" nillable="true" minOccurs="0"/>
            <xsd:element name="alternative-names" type="xsd:string" nillable="true" minOccurs="0"/>
            <xsd:element name="modified" type="xsd:date" nillable="true" minOccurs="0"/>
            <xsd:element name="created" type="xsd:date" nillable="true" minOccurs="0"/>
            <xsd:element name="icon" type="xsd:string" nillable="true" minOccurs="0"/>
            <xsd:element name="item" type="xsd:string" nillable="true" minOccurs="0"/>
            <xsd:element name="label" type="xsd:string" nillable="true" minOccurs="0"/>
            <xsd:element name="id" type="xsd:string" nillable="true" minOccurs="0"/>
        </xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== Tony7466/datacrow/modules/datacrow-resources/modules/data/movie_genre.xml
<?xml version="1.0" encoding="UTF-8" ?>
<data-crow-objects xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="movie_genre.xsd">
    <movie-genre-items>
            <movie-genre>
                <picture-01></picture-01>
                <picture-02></picture-02>
                <picture-03></picture-03>
                <picture-04></picture-04>
                <picture-05></picture-05>
                <picture-06></picture-06>
                <picture-07></picture-07>
                <picture-08></picture-08>
                <picture-09></picture-09>
                <picture-10></picture-10>
                <name>Action</name>
                <modified>2024-10-01</modified>
                <created>2024-10-01</created>
                <label>Action</label>
                <id>101769732545758</id>
            </movie-genre>
            <movie-genre>
                <picture-01></picture-01>
                <picture-02></picture-02>
                <picture-03></picture-03>
                <picture-04></picture-04>
                <picture-05></picture-05>
                <picture-06></picture-06>
                <picture-07></picture-07>
                <picture-08></picture-08>
                <picture-09></picture-09>
                <picture-10></picture-10>
                <name>Adult Film</name>
                <alternative-names>;porn;erotic;</alternative-names>
                <modified>2024-10-01</modified>
                <created>2024-10-01</created>
                <label>Adult Film</label>
                <id>101753357919454</id>
            </movie-genre>
            <movie-genre>
                <picture-01></picture-01>
                <picture-02></picture-02>
                <picture-03></picture-03>
                <picture-04></picture-04>
                <picture-05></picture-05>
                <picture-06></picture-06>
                <picture-07></picture-07>
                <picture-08></picture-08>
                <picture-09></picture-09>
                <picture-10></picture-10>
                <name>Adventure</name>
                <modified>2024-10-01</modified>
                <created>2024-10-01</created>
                <label>Adventure</label>
                <id>101782073228135</id>
            </movie-genre>
            <movie-genre>
                <picture-01></picture-01>
                <picture-02></picture-02>
                <picture-03></picture-03>
                <picture-04></picture-04>
                <picture-05></picture-05>
                <picture-06></picture-06>
                <picture-07></picture-07>
                <picture-08></picture-08>
                <picture-09></picture-09>
                <picture-10></picture-10>
                <name>Animation</name>
                <modified>2024-10-01</modified>
                <created>2024-10-01</created>
                <label>Animation</label>
                <id>101771618977776</id>
            </movie-genre>
            <movie-genre>
                <picture-01></picture-01>
                <picture-02></picture-02>
                <picture-03></picture-03>
                <picture-04></picture-04>
                <picture-05></picture-05>
                <picture-06></picture-06>
                <picture-07></picture-07>
                <picture-08></picture-08>
                <picture-09></picture-09>
                <picture-10></picture-10>
                <name>Children&apos;s Film</name>
                <alternative-names>;Children;</alternative-names>
                <modified>2024-10-01</modified>
                <created>2024-10-01</created>
                <label>Children&apos;s Film</label>
                <id>101711011271608</id>
            </movie-genre>
            <movie-genre>
                <picture-01></picture-01>
                <picture-02></picture-02>
                <picture-03></picture-03>
                <picture-04></picture-04>
                <picture-05></picture-05>
                <picture-06></picture-06>
                <picture-07></picture-07>
                <picture-08></picture-08>
                <picture-09></picture-09>
                <picture-10></picture-10>
                <name>Comedy</name>
                <modified>2024-10-01</modified>
                <created>2024-10-01</created>
                <label>Comedy</label>
                <id>101782248464045</id>
            </movie-genre>
            <movie-genre>
                <picture-01></picture-01>
                <picture-02></picture-02>
                <picture-03></picture-03>
                <picture-04></picture-04>
                <picture-05></picture-05>
                <picture-06></picture-06>
                <picture-07></picture-07>
                <picture-08></picture-08>
                <picture-09></picture-09>
                <picture-10></picture-10>
                <name>Crime</name>
                <modified>2024-10-01</modified>
                <created>2024-10-01</created>
                <label>Crime</label>
                <id>101734189383151</id>
            </movie-genre>
            <movie-genre>
                <picture-01></picture-01>
                <picture-02></picture-02>
                <picture-03></picture-03>
                <picture-04></picture-04>
                <picture-05></picture-05>
                <picture-06></picture-06>
                <picture-07></picture-07>
                <picture-08></picture-08>
                <picture-09></picture-09>
                <picture-10></picture-10>
                <name>Documentary</name>
                <modified>2024-10-01</modified>
                <created>2024-10-01</created>
                <label>Documentary</label>
                <id>101776928584555</id>
            </movie-genre>
            <movie-genre>
                <picture-01></picture-01>
                <picture-02></picture-02>
                <picture-03></picture-03>
                <picture-04></picture-04>
                <picture-05></picture-05>
                <picture-06></picture-06>
                <picture-07></picture-07>
                <picture-08></picture-08>
                <picture-09></picture-09>
                <picture-10></picture-10>
                <name>Drama</name>
                <modified>2024-10-01</modified>
                <created>2024-10-01</created>
                <label>Drama</label>
                <id>101719258739166</id>
            </movie-genre>
            <movie-genre>
                <picture-01></picture-01>
                <picture-02></picture-02>
                <picture-03></picture-03>
                <picture-04></picture-04>
                <picture-05></picture-05>
                <picture-06></picture-06>
                <picture-07></picture-07>
                <picture-08></picture-08>
                <picture-09></picture-09>
                <picture-10></picture-10>
                <name>Family Film</name>
                <alternative-names>;Family;</alternative-names>
                <modified>2024-10-01</modified>
                <created>2024-10-01</created>
                <label>Family Film</label>
                <id>101760952839699</id>
            </movie-genre>
            <movie-genre>
                <picture-01></picture-01>
                <picture-02></picture-02>
                <picture-03></picture-03>
                <picture-04></picture-04>
                <picture-05></picture-05>
                <picture-06></picture-06>
                <picture-07></picture-07>
                <picture-08></picture-08>
                <picture-09></picture-09>
                <picture-10></picture-10>
                <name>Fantasy</name>
                <modified>2024-10-01</modified>
                <created>2024-10-01</created>
                <label>Fantasy</label>
                <id>101757770563423</id>
            </movie-genre>
            <movie-genre>
                <picture-01></picture-01>
                <picture-02></picture-02>
                <picture-03></picture-03>
                <picture-04></picture-04>
                <picture-05></picture-05>
                <picture-06></picture-06>
                <picture-07></picture-07>
                <picture-08></picture-08>
                <picture-09></picture-09>
                <picture-10></picture-10>
                <name>Film Noir</name>
                <modified>2024-10-01</modified>
                <created>2024-10-01</created>
                <label>Film Noir</label>
                <id>101764575296561</id>
            </movie-genre>
            <movie-genre>
                <picture-01></picture-01>
                <picture-02></picture-02>
                <picture-03></picture-03>
                <picture-04></picture-04>
                <picture-05></picture-05>
                <picture-06></picture-06>
                <picture-07></picture-07>
                <picture-08></picture-08>
                <picture-09></picture-09>
                <picture-10></picture-10>
                <name>Historical</name>
                <modified>2024-10-01</modified>
                <created>2024-10-01</created>
                <label>Historical</label>
                <id>101781341292759</id>
            </movie-genre>
            <movie-genre>
                <picture-01></picture-01>
                <picture-02></picture-02>
                <picture-03></picture-03>
                <picture-04></picture-04>
                <picture-05></picture-05>
                <picture-06></picture-06>
                <picture-07></picture-07>
                <picture-08></picture-08>
                <picture-09></picture-09>
