=== Tony7466/datacrow/Modules/datacrow-resources/modules/data/music_album_state.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xsd:element name="data-crow-objects">
    <xsd:complexType>
        <xsd:sequence>
            <xsd:element name="music_album_state-items" type ="music_album_state-items-type"/>
        </xsd:sequence>
    </xsd:complexType>
</xsd:element>

    <xsd:complexType name="music_album_state-items-type" >
        <xsd:sequence>
            <xsd:element type="music_album_state-type" name="music_album_state" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="music_album_state-type" >
        <xsd:sequence>
            <xsd:element name="picture-01" type="xsd:string" nillable="true" minOccurs="0"/>
            <xsd:element name="picture-02" type="xsd:string" nillable="true" minOccurs="0"/>
            <xsd:element name="picture-03" type="xsd:string" nillable="true" minOccurs="0"/>
            <xsd:element name="picture-04" type="xsd:string" nillable="true" minOccurs="0"/>
            <xsd:element name="picture-05" type="xsd:string" nillable="true" minOccurs="0"/>
            <xsd:element name="picture-06" type="xsd:string" nillable="true" minOccurs="0"/>
            <xsd:element name="picture-07" type="xsd:string" nillable="true" minOccurs="0"/>
            <xsd:element name="picture-08" type="xsd:string" nillable="true" minOccurs="0"/>
            <xsd:element name="picture-09" type="xsd:string" nillable="true" minOccurs="0"/>
            <xsd:element name="picture-10" type="xsd:string" nillable="true" minOccurs="0"/>
            <xsd:element name="name" type="xsd:string" nillable="true" minOccurs="0"/>
            <xsd:element name="alternative-names" type="xsd:string" nillable="true" minOccurs="0"/>
            <xsd:element name="modified" type="xsd:date" nillable="true" minOccurs="0"/>
            <xsd:element name="created" type="xsd:date" nillable="true" minOccurs="0"/>
            <xsd:element name="icon" type="xsd:string" nillable="true" minOccurs="0"/>
            <xsd:element name="item" type="xsd:string" nillable="true" minOccurs="0"/>
            <xsd:element name="label" type="xsd:string" nillable="true" minOccurs="0"/>
            <xsd:element name="id" type="xsd:string" nillable="true" minOccurs="0"/>
        </xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== Tony7466/datacrow/Modules/datacrow-resources/modules/data/music_album_state.xml
<?xml version="1.0" encoding="UTF-8" ?>
<data-crow-objects xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="music_album_state.xsd">
    <state-items>
            <state>
                <name>Heard</name>
                <modified>2024-10-01</modified>
                <created>2024-10-01</created>
                <icon>R0lGODlhDwAPALMLAAAAAADMmQDMZgCZZgD/mRAAADPMmTOZZjPMZgCZmTOZmQAAAAAAAAAAAAAAAAAAACH5BAEAAAsALAAAAAAPAA8AAARMcMlJF7g1gyACyBRABB4oiVxhnsH4mRshqCc2beQLDLzOBTTLgHAYfAAdxMsiUJAEG0MpJBiQDtVpyDDokIKVnUHAXWoECePqVDBPIgA7</icon>
                <label>Heard</label>
                <id>101711157809329</id>
            </state>
            <state>
                <name>Lost</name>
                <modified>2024-10-01</modified>
                <created>2024-10-01</created>
                <icon>R0lGODlhDgAMALMPAAAAAP9mZswzM/8zM8xmZv8zZrwAAAAYAJkAAMxmM/9mM8wAM8wzAAAAEOcAAAAAACH5BAEAAA8ALAAAAAAOAAwAAARFEMj53rwhZ6kHAVYgCAEyiCJYAcFJksNRzSwcJM2ss0nx6btAQSFQAWuogXHVEpFSNBTBgShkFiCWS3kwCBgCw4ViGUcAADs=</icon>
                <label>Lost</label>
                <id>101723576043420</id>
            </state>
            <state>
                <name>Not heard</name>
                <modified>2024-10-01</modified>
                <created>2024-10-01</created>
                <icon>R0lGODlhDgAQALMPAAAAAMzMzJmZmcwzM60AAOfn58xmZu/378xmmf+ZmcwzZpkAM/+ZzAAYAMwAMwAAACH5BAEAAA8ALAAAAAAOABAAAARi8MlJG50NTDA0BUUBjAPSbY4RckN5sooCEEQ3PsARGsayjIeABhDQGRAJHiMgxAkEhkQixEg2Ac9jsRAwDK7PgULADAwIYEHtyaSlaeQ2wTNSE9iB+WV0L3suOFhNgB9/ExEAOw==</icon>
                <label>Not heard</label>
                <id>101780806671707</id>
            </state>
            <state>
                <name>Want to have</name>
                <modified>2024-10-01</modified>
                <created>2024-10-01</created>
                <icon>R0lGODlhDwAPALMAAAAAAACEAADGAITG/4T/hP///////////////////////////////////////4DA/yH5BAEAAA8ALAAAAAAPAA8AAARB8EkJap34WcLtpRwnCKEAgMSoqsGppWMgzy0Ye549hl0GBCsVwTX50Vgu3OaG4sEEtVeQFQVAZbEZEaf9ZDQ5TAQAOw==</icon>
                <label>Want to have</label>
                <id>101772276479019</id>
            </state>
        </state-items>
</data-crow-objects>

=== Tony7466/datacrow/modules/datacrow-resources/modules/data/music_album_state.xml
<?xml version="1.0" encoding="UTF-8" ?>
<data-crow-objects xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="music_album_state.xsd">
    <state-items>
            <state>
                <datacrow-module-index>15068</datacrow-module-index>
                <picture-01></picture-01>
                <picture-02></picture-02>
                <picture-03></picture-03>
                <picture-04></picture-04>
                <picture-05></picture-05>
                <picture-06></picture-06>
                <picture-07></picture-07>
                <picture-08></picture-08>
                <picture-09></picture-09>
                <picture-10></picture-10>
                <name>Heard</name>
                <modified>2025-04-17</modified>
                <created>2025-04-17</created>
                <icon>R0lGODlhDwAPALMLAAAAAADMmQDMZgCZZgD/mRAAADPMmTOZZjPMZgCZmTOZmQAAAAAAAAAAAAAAAAAAACH5BAEAAAsALAAAAAAPAA8AAARMcMlJF7g1gyACyBRABB4oiVxhnsH4mRshqCc2beQLDLzOBTTLgHAYfAAdxMsiUJAEG0MpJBiQDtVpyDDokIKVnUHAXWoECePqVDBPIgA7</icon>
                <label>Heard</label>
                <id>101711157809329</id>
            </state>
            <state>
                <datacrow-module-index>15068</datacrow-module-index>
                <picture-01></picture-01>
                <picture-02></picture-02>
                <picture-03></picture-03>
                <picture-04></picture-04>
                <picture-05></picture-05>
                <picture-06></picture-06>
                <picture-07></picture-07>
                <picture-08></picture-08>
                <picture-09></picture-09>
                <picture-10></picture-10>
                <name>Lost</name>
                <modified>2025-04-17</modified>
                <created>2025-04-17</created>
                <icon>R0lGODlhDgAMALMPAAAAAP9mZswzM/8zM8xmZv8zZrwAAAAYAJkAAMxmM/9mM8wAM8wzAAAAEOcAAAAAACH5BAEAAA8ALAAAAAAOAAwAAARFEMj53rwhZ6kHAVYgCAEyiCJYAcFJksNRzSwcJM2ss0nx6btAQSFQAWuogXHVEpFSNBTBgShkFiCWS3kwCBgCw4ViGUcAADs=</icon>
                <label>Lost</label>
                <id>101723576043420</id>
            </state>
            <state>
                <datacrow-module-index>15068</datacrow-module-index>
                <picture-01></picture-01>
                <picture-02></picture-02>
                <picture-03></picture-03>
                <picture-04></picture-04>
                <picture-05></picture-05>
                <picture-06></picture-06>
                <picture-07></picture-07>
                <picture-08></picture-08>
                <picture-09></picture-09>
                <picture-10></picture-10>
                <name>Not heard</name>
                <modified>2025-04-17</modified>
                <created>2025-04-17</created>
                <icon>R0lGODlhDgAQALMPAAAAAMzMzJmZmcwzM60AAOfn58xmZu/378xmmf+ZmcwzZpkAM/+ZzAAYAMwAMwAAACH5BAEAAA8ALAAAAAAOABAAAARi8MlJG50NTDA0BUUBjAPSbY4RckN5sooCEEQ3PsARGsayjIeABhDQGRAJHiMgxAkEhkQixEg2Ac9jsRAwDK7PgULADAwIYEHtyaSlaeQ2wTNSE9iB+WV0L3suOFhNgB9/ExEAOw==</icon>
                <label>Not heard</label>
                <id>101780806671707</id>
            </state>
            <state>
                <datacrow-module-index>15068</datacrow-module-index>
                <picture-01></picture-01>
                <picture-02></picture-02>
                <picture-03></picture-03>
                <picture-04></picture-04>
                <picture-05></picture-05>
                <picture-06></picture-06>
                <picture-07></picture-07>
                <picture-08></picture-08>
                <picture-09></picture-09>
                <picture-10></picture-10>
                <name>Want to have</name>
                <modified>2025-04-17</modified>
                <created>2025-04-17</created>
                <icon>R0lGODlhDwAPALMAAAAAAACEAADGAITG/4T/hP///////////////////////////////////////4DA/yH5BAEAAA8ALAAAAAAPAA8AAARB8EkJap34WcLtpRwnCKEAgMSoqsGppWMgzy0Ye549hl0GBCsVwTX50Vgu3OaG4sEEtVeQFQVAZbEZEaf9ZDQ5TAQAOw==</icon>
                <label>Want to have</label>
                <id>101772276479019</id>
            </state>
        </state-items>
</data-crow-objects>
